name: poc
run-name: poc (${{ inputs.test }})

on:
  workflow_dispatch:
    inputs:
      test:
        type: string
        description: test

env:
  TEST_VAR: ${{ github.event.inputs.test }}
  LEAK: secret-value

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Set new build metadata
        id: build-metadata
        run: |
          echo $TEST_VAR
